"""Tests for pulling the big embedded thumbnail out of a sliced gcode."""

from __future__ import annotations

import base64
import struct
import zlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

from custom_components.elegoo_printer.job_previews import extract_gcode_thumbnail


def _png(w: int, h: int) -> bytes:
    """Return a tiny but valid PNG of the given declared size."""

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    idat = zlib.compress(b"\x00" + b"\x00\x00\x00" * w)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", idat)
        + chunk(b"IEND", b"")
    )


def _block(png: bytes, w: int, h: int) -> str:
    b64 = base64.b64encode(png).decode()
    lines = [f"; thumbnail begin {w}x{h} {len(b64)}"]
    lines += [f"; {b64[i : i + 78]}" for i in range(0, len(b64), 78)]
    lines.append("; thumbnail end")
    return "\n".join(lines)


def _gcode(tmp_path: Path, *sizes: int) -> Path:
    body = [
        "; HEADER_BLOCK_START",
        "; generated by ElegooSlicer",
        "; THUMBNAIL_BLOCK_START",
    ]
    body.extend(_block(_png(s, s), s, s) for s in sizes)
    body += ["; THUMBNAIL_BLOCK_END", "G28", "G1 X0 Y0", "M104 S200"]
    p = tmp_path / "job.gcode"
    p.write_text("\n".join(body) + "\n")
    return p


def test_picks_the_largest_thumbnail(tmp_path: Path) -> None:
    png = extract_gcode_thumbnail(_gcode(tmp_path, 144, 512))
    assert png is not None
    w, h = struct.unpack(">II", png[16:24])
    assert (w, h) == (512, 512)


def test_order_does_not_matter(tmp_path: Path) -> None:
    png = extract_gcode_thumbnail(_gcode(tmp_path, 512, 144))
    w, h = struct.unpack(">II", png[16:24])
    assert (w, h) == (512, 512)


def test_single_small_thumbnail_still_works(tmp_path: Path) -> None:
    png = extract_gcode_thumbnail(_gcode(tmp_path, 144))
    w, h = struct.unpack(">II", png[16:24])
    assert (w, h) == (144, 144)


def test_no_thumbnail_returns_none(tmp_path: Path) -> None:
    p = tmp_path / "plain.gcode"
    p.write_text("G28\nG1 X0 Y0\nM104 S200\n")
    assert extract_gcode_thumbnail(p) is None


def test_missing_file_returns_none(tmp_path: Path) -> None:
    assert extract_gcode_thumbnail(tmp_path / "nope.gcode") is None
